home_url: http://naturecloud.io
google_analytics_code: UA-57776306-2
github:
    enabled: false
    position: top
    tree: https://github.com/naturecloud/docs/blob/master/
    commits: https://github.com/naturecloud/docs/commits/develop/
